services:
  client:
    image: "jbur645/multicontainerdeploy-client"
    mem_limit: 512m
    hostname: client
  server:
    image: "jbur645/multicontainerdeploy-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "jbur645/multicontainerdeploy-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: "jbur645/multicontainerdeploy-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
