name: Deploy MultiContianer
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build test image
        run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true cygnetops/react-test npm test

      - name: Build docker image:
        run: docker build -t cygnetops/multicontainerdeploy-client-7-25 ./client
        run: docker build -t cygnetops/multicontainerdeploy-nginx-7-25 ./nginx
        run: docker build -t cygnetops/multicontainerdeploy-server-7-25 ./server
        run: docker build -t cygnetops/multicontainerdeploy-worker-7-25 ./worker

      - name: Push to Dockerhub:
        run: docker push -t cygnetops/multicontainerdeploy-client-7-25
        run: docker push -t cygnetops/multicontainerdeploy-nginx-7-25
        run: docker push -t cygnetops/multicontainerdeploy-server-7-25
        run: docker push -t cygnetops/multicontainerdeploy-worker-7-25

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multicontainerdeploy
          environment_name: Multicontainerdeploy-env
          existing_bucket_name: elasticbeanstalk-us-east-2-526802959187
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip


#when setting up and EB environment, make sure the application name and env name match.