name: Deploy MultiContianer
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKER_USER_ID }}/multicontainerdeploy-client:7-25


      - name: Build and push nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKER_USER_ID }}/multicontainerdeploy-nginx:7-25


      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USER_ID }}/multicontainerdeploy-server:7-25


      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: ${{ secrets.DOCKER_USER_ID }}/multicontainerdeploy-worker:7-25


      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}

          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-container
          environment_name: Multi-container-env

          existing_bucket_name: elasticbeanstalk-us-east-2-526802959187
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip


#when setting up and EB environment, make sure the application name and env name match.

